### ISSUE TITLE
@example turning into @apiExample

### ISSUE THREAD

**Issue by maikelmclauflin** [spadgos/sublime-jsdocs#425] opened 2016-09-28 14:26 UTC
name says it all. what gives? am i missing a setting somewhere?

**Comment by gerardroche** [comment] 2016-09-30 08:29
Which language? Can you show more details, a specific example might help, because I can't reproduce it.

**Comment by maikelmclauflin** [comment] 2016-10-02 21:32
sorry, this was an error on my end. i installed 2 snippet packages at the same time unfortunately that other (crappier looking) one kept winning out. thanks for your response though

**Comment by gerardroche** [comment] 2016-10-03 12:14
:) no worries. Please close the issue.

**Closed as completed** 2016-10-04 14:19 UTC
