### ISSUE TITLE
Please add c# support

### ISSUE THREAD

**Issue by fishg** [spadgos/sublime-jsdocs#327] opened 2014-11-19 11:05 UTC
Please add c# support.Thanks.

**Comment by bsqsbylt** [comment] 2015-06-11 10:30
Please add c# support.Thanks.

**Comment by spadgos** [comment] 2015-06-15 13:47
Please add c# support.Thanks.

**Comment by 20Tauri** [comment] 2015-09-18 06:35
I currently develop an alternative to DocBlockr called DoxyDoxygen
This language is supported.
See [Compare Doxygen to DocBlockr](https://github.com/20Tauri/DoxyDoxygen/blob/master/COMPARE.md) for details
Perhaps you may try it.
I am interested by any feedback

**Comment by jenlampton** [comment] 2016-08-28 22:52
Looks like this is a dupe of https://github.com/spadgos/sublime-jsdocs/issues/220?

**Closed** 2016-09-05 08:06 UTC
Labels: Language request
